import './globals.css';
import AuthProvider from './AuthProvider';
import NavMenu from './NavMenu';

interface Props {
  children: React.ReactNode;
}

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: Props) {
  return (
    <AuthProvider>
      <html lang="en">
        <body>
          <div className="container">
            <NavMenu />
            <main>{children}</main>
          </div>
        </body>
      </html>
    </AuthProvider>
  );
}
